# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Callisto 4 Demo Templates
email: bruno@brunofenzl.com

baseurl: "/callisto4" # the subpath of your site, e.g. /blog
url: "https://frontend-studios.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
include: [dist/scripts/, dist/styles/, dist/images, dist/fonts]
exclude: [/node_modules, /bower_components, bower.json, package.json, /css]
